---
- name: "Update apt packages."
  become: true
  apt:
    update_cache: yes

- name: "Upgrade packages"
  become: true
  apt:
    upgrade: 'yes'


- name: "Remove dependencies that are no longer required"
  become: true
  apt:
    autoremove: yes

- name: "Install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "Install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "List Content"
  become: true
  shell: |
    ls -la
    tar --version

- name: "Copy artifact to home directory"
  copy:
    src: "files/artifact.tar.gz"
    dest: "~/artifact.tar.gz"

- name: "List Content"
  become: true
  shell: |
    ls -la
    tar --version

- name: "Uncompress and rename directory"
  become: true
  shell: |
    tar -xzvf artifact.tar.gz
    mv backend web

- name: "Install backend dependencies"
  become: true
  shell: |
    cd web
    npm install

- name: "Start server"
  become: true
  shell: |
    cd web
    pm2 start npm -- start