---
- name: "Update apt packages."
  become: true
  apt:
    update_cache: yes

- name: "Upgrade packages"
  become: true
  apt:
    upgrade: 'yes'


- name: "Remove dependencies that are no longer required"
  become: true
  apt:
    autoremove: yes

- name: "Install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "Install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Decompress local archive to remote server"
  unarchive:
    src: "files/artifact.tar.gz"
    dest: "~/"

- name: "Rename directory from backend to web"
  become: true
  shell: |
    #mv backend web
    cp -r backend/* web

- name: "Start server"
  become: true
  shell: |
    cd web
    pm2 start npm -- start