Description: UdaPeople frontend stack


Parameters:
  # New Bucket name
  BlueBucketID:
    Description: Unique identifier
    Type: String

Resources:
  BlueWebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${BlueBucketID}"
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref 'BlueWebsiteBucket'
      PolicyDocument:
        Statement:
        - Sid: PublicReadForGetBucketObjects
          Effect: Allow
          Principal: '*'
          Action: s3:GetObject
          Resource: !Join ['', ['arn:aws:s3:::', !Ref 'BlueWebsiteBucket', /*]]

Outputs:
  WebsiteURL:
    Value: !GetAtt BlueWebsiteBucket.WebsiteURL
    Description: URL for website hosted on S3

  BucketID:
    Description: s3 Bucket for hosting content
    Value: !Sub ${BlueBucketID}
    Export:
      Name: BlueBucketID

  BlueWebsiteBucket:
    Description: Bucket Created using this template.
    Value: !Ref BlueWebsiteBucket
    Export:
      Name: BlueWebsiteBucket

# Description: >
#   UdaPeople frontend stack.

# Parameters:
#   ID:
#     Description: Unique identifier.
#     Type: String

# Resources:
#   WebsiteBucket:
#     Type: AWS::S3::Bucket
#     Properties:
#       BucketName: !Sub "udapeople-${ID}"
#       AccessControl: PublicRead
#       WebsiteConfiguration:
#         IndexDocument: index.html
#         ErrorDocument: 404.html
  
#   WebsiteBucketPolicy:
#     Type: AWS::S3::BucketPolicy
#     Properties:
#       Bucket: !Ref 'WebsiteBucket'
#       PolicyDocument:
#         Statement:
#         - Sid: PublicReadForGetBucketObjects
#           Effect: Allow
#           Principal: '*'
#           Action: s3:GetObject
#           Resource: !Join ['', ['arn:aws:s3:::', !Ref 'WebsiteBucket', /*]]

# Outputs:
#   WebsiteURL:
#     Value: !GetAtt WebsiteBucket.WebsiteURL
#     Description: URL for website hosted on S3
